### ISSUE TITLE
Console Buffer Overwrite

### ISSUE THREAD

**Issue by valkyrienyanko** [valkyrienyanko/The-MMORPG-Project#6]
After 5 rows of output, the output buffer will overwrite the 5th row over and over again.

![Preview](https://i.gyazo.com/8335bcdae680017884ca9b23b25ef185.gif)

**Comment by Shepardeon** [comment]
I'm unable to replicate on my end:
![image](https://user-images.githubusercontent.com/15271735/82140080-7c9f8200-982d-11ea-9431-f528d005d54a.png)
